### ISSUE TITLE
Follow the theme design for the submit button

### ISSUE THREAD

**Issue by zu** [epiphyt/form-block#7]
### What feature are you requesting?

The form's submit button should look like the theme design's button style.
This doesn't work out of the box and can't be overriden with adding the class "wp-block-button__link" or "wp-element-button" (see screenshot)

![2023-04-10-button](https://user-images.githubusercontent.com/147629/230923406-5efb6cc1-0055-4dcf-84d3-ae8579e175d6.png)

### Why is this feature necessary?

I think, this should be default behaviour.

### Are you expecing side-effects?

no, except that Im hesitant to use the plugin like this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zu** [comment]
btw, if I sound a bit unfriendly, I'm sorry! It wasn't meant like this, but now I feel "being hesitant to use the plugin like this" sounds very harsh which wasn't my intent. I really like how the form works. 

Thanks for your quick replay. I tried to work around it with theme.json but couldn't figure it out.

Interestingly the reset button looks different then the submit button (but also not the same as the theme default)

**Comment by zu** [comment]
https://user-images.githubusercontent.com/147629/231100368-4f919e96-3ee8-4de8-b88b-1cba25fb13f7.mp4

I realized that the label/name of the button doesn't adjust to the input in the Name field and is even submit for the reset button.

**Comment by MatzeKitt** [comment]
Can you please create a separate issue for that?

**Comment by zu** [comment]
Sure.
Created a new issue: https://github.com/epiphyt/form-block/issues/8
